workflows:
  ios-capacitor:
    name: Capacitor iOS Build
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      vars:
        NODE_VERSION: "18"
      xcode: latest

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Build web app
        script: |
          npm run build

      - name: Sync Capacitor
        script: |
          npx cap sync ios

      - name: Build iOS archive
        script: |
          xcodebuild \
            -workspace ios/App/App.xcworkspace \
            -scheme App \
            -configuration Release \
            -sdk iphoneos \
            -archivePath build/App.xcarchive \
            archive

    artifacts:
      - build/App.xcarchive
